export type ConditionTrigger = 'start_of_turn' | 'end_of_turn' | 'manual';

export interface Condition {
    id: string;
    name: string;
    iconName: string; // Lucide icon name
    description: string;
    mechanicalSummary: string;
    endTrigger: ConditionTrigger;
    duration: number; // Rounds remaining, -1 = indefinite
}

export const CONDITIONS: Condition[] = [
    {
        id: 'blinded',
        name: 'Blinded',
        iconName: 'EyeOff',
        description: "A blinded creature can't see and automatically fails any ability check that requires sight.",
        mechanicalSummary: "Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'charmed',
        name: 'Charmed',
        iconName: 'Heart',
        description: "A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
        mechanicalSummary: "The charmer has advantage on any ability check to interact socially with the creature.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'deafened',
        name: 'Deafened',
        iconName: 'EarOff',
        description: "A deafened creature can't hear and automatically fails any ability check that requires hearing.",
        mechanicalSummary: "Fails ability checks that require hearing.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'frightened',
        name: 'Frightened',
        iconName: 'Ghost',
        description: "A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
        mechanicalSummary: "The creature can't willingly move closer to the source of its fear.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'grappled',
        name: 'Grappled',
        iconName: 'Hand',
        description: "A grappled creature's speed becomes 0, and it can't benefit from any bonus to its speed.",
        mechanicalSummary: "Speed 0. The condition ends if the grappler is incapacitated or if an effect removes the grappled creature from the reach of the grappler.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'incapacitated',
        name: 'Incapacitated',
        iconName: 'Ban',
        description: "An incapacitated creature can't take actions or reactions.",
        mechanicalSummary: "No actions or reactions.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'invisible',
        name: 'Invisible',
        iconName: 'Cloud',
        description: "An invisible creature is impossible to see without the aid of magic or a special sense.",
        mechanicalSummary: "For the purpose of hiding, the creature is heavily obscured. Attack rolls against the creature have disadvantage, and the creature's attack rolls have advantage.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'paralyzed',
        name: 'Paralyzed',
        iconName: 'ZapOff',
        description: "A paralyzed creature is incapacitated and can't move or speak.",
        mechanicalSummary: "The creature automatically fails Strength and Dexterity saving throws. Attack rolls against the creature have advantage. Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'petrified',
        name: 'Petrified',
        iconName: 'Mountain',
        description: "A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone).",
        mechanicalSummary: "Its weight increases by a factor of ten, and it ceases aging. The creature is incapacitated, can't move or speak, and is unaware of its surroundings. Attack rolls against the creature have advantage. The creature automatically fails Strength and Dexterity saving throws. The creature has resistance to all damage. The creature is immune to poison and disease, although poison or disease already in its system is suspended, not neutralized.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'poisoned',
        name: 'Poisoned',
        iconName: 'FlaskConical',
        description: "A poisoned creature has disadvantage on attack rolls and ability checks.",
        mechanicalSummary: "Disadvantage on attack rolls and ability checks.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'prone',
        name: 'Prone',
        iconName: 'ArrowDown',
        description: "A prone creature's only movement option is to crawl, unless it stands up and thereby ends the condition.",
        mechanicalSummary: "The creature has disadvantage on attack rolls. An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'restrained',
        name: 'Restrained',
        iconName: 'Link',
        description: "A restrained creature's speed becomes 0, and it can't benefit from any bonus to its speed.",
        mechanicalSummary: "Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage. The creature has disadvantage on Dexterity saving throws.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'stunned',
        name: 'Stunned',
        iconName: 'Star',
        description: "A stunned creature is incapacitated, can't move, and can speak only falteringly.",
        mechanicalSummary: "The creature automatically fails Strength and Dexterity saving throws. Attack rolls against the creature have advantage.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'unconscious',
        name: 'Unconscious',
        iconName: 'Moon',
        description: "An unconscious creature is incapacitated, can't move or speak, and is unaware of its surroundings.",
        mechanicalSummary: "The creature drops whatever it's holding and falls prone. The creature automatically fails Strength and Dexterity saving throws. Attack rolls against the creature have advantage. Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'exhaustion-1',
        name: 'Exhaustion (Level 1)',
        iconName: 'Zap',
        description: "Disadvantage on ability checks.",
        mechanicalSummary: "Disadvantage on ability checks.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'exhaustion-2',
        name: 'Exhaustion (Level 2)',
        iconName: 'Zap',
        description: "Speed halved.",
        mechanicalSummary: "Speed halved.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'exhaustion-3',
        name: 'Exhaustion (Level 3)',
        iconName: 'Zap',
        description: "Disadvantage on attack rolls and saving throws.",
        mechanicalSummary: "Disadvantage on attack rolls and saving throws.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'exhaustion-4',
        name: 'Exhaustion (Level 4)',
        iconName: 'Zap',
        description: "Hit point maximum halved.",
        mechanicalSummary: "Hit point maximum halved.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'exhaustion-5',
        name: 'Exhaustion (Level 5)',
        iconName: 'Zap',
        description: "Speed reduced to 0.",
        mechanicalSummary: "Speed reduced to 0.",
        endTrigger: 'manual',
        duration: -1,
    },
    {
        id: 'exhaustion-6',
        name: 'Exhaustion (Level 6)',
        iconName: 'Zap',
        description: "Death.",
        mechanicalSummary: "Death.",
        endTrigger: 'manual',
        duration: -1,
    },
];
